"""Citation formatting engine for sci-writing skill.

Parses .bib files generated by sci-literature-research and formats citations
in APA 7th, Nature, IEEE, and Vancouver styles. Per D-08: reads .bib files
produced by sci-literature-research. Per D-09: supports 4 styles minimum.

Functions:
    parse_bib_file - Parse a .bib file into a list of entry dicts
    format_citation - Format a single bibliography entry in a given style
    format_intext - Generate an in-text citation string
    format_bibliography - Generate a full references section
    replace_citation_markers - Replace [@key] markers in draft text
"""

import re
import sys
import urllib.parse
from pathlib import Path

# Add project root to sys.path for repro import
sys.path.insert(0, str(Path(__file__).resolve().parents[4]))
from repro.repro_logger import log_operation


SUPPORTED_STYLES = ("apa", "nature", "ieee", "vancouver")


# ---------------------------------------------------------------------------
# BibTeX Parsing
# ---------------------------------------------------------------------------


_BIB_COMMENT_LINE_RE = re.compile(r"^\s*%.*$", re.MULTILINE)


def _strip_bib_comments(text: str) -> str:
    """Remove BibTeX `%`-prefixed comment lines.

    Phase 9: a previous bug let `% gray_lit = {approved}` (a commented-out
    approval) be parsed as if live, because the field regex matched anywhere
    in the entry body. BibTeX comments must be stripped before the entry
    parser ever sees them — both to avoid silent escape-hatch leakage and
    to match BibTeX's documented behaviour.
    """
    return _BIB_COMMENT_LINE_RE.sub("", text)


def parse_bib_file(filepath: str) -> list[dict]:
    """Parse a .bib file into a list of structured entry dicts.

    Each entry dict contains: entry_type, key, title, author, year, and any
    other fields present (journal, doi, url, eprint, booktitle, etc.).

    Returns an empty list for missing or empty files.
    """
    path = Path(filepath)
    if not path.exists():
        return []

    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return []

    # Phase 9: strip `%`-prefixed comment lines so commented-out approvals
    # cannot leak into the parsed entry. Without this, `% gray_lit = {approved}`
    # would be parsed as a live field by the body regex below.
    text = _strip_bib_comments(text)

    entries = []
    # Match each @type{key, ... } block
    pattern = re.compile(r"@(\w+)\{([^,]+),\s*(.*?)\n\}", re.DOTALL)

    for match in pattern.finditer(text):
        entry_type = match.group(1).lower()
        key = match.group(2).strip()
        body = match.group(3)

        entry: dict = {"entry_type": entry_type, "key": key}

        # Parse individual fields: fieldname = {value}
        field_pattern = re.compile(r"(\w+)\s*=\s*\{(.*?)\}(?:\s*,|\s*$)", re.DOTALL)
        for field_match in field_pattern.finditer(body):
            field_name = field_match.group(1).lower()
            field_value = field_match.group(2).strip()

            # Strip double braces from title: {{Title}} -> Title
            if field_value.startswith("{") and field_value.endswith("}"):
                field_value = field_value[1:-1]

            entry[field_name] = field_value

        entries.append(entry)

    return entries


# ---------------------------------------------------------------------------
# Author Formatting Helpers
# ---------------------------------------------------------------------------


def _parse_author_parts(author_str: str) -> list[tuple[str, str]]:
    """Split an author string into list of (last_name, first_name) tuples.

    Handles 'Last, First and Last, First' format from BibTeX.
    Also handles LaTeX special chars like {\"u} in names.
    """
    authors = []
    for part in author_str.split(" and "):
        part = part.strip()
        if not part:
            continue
        if "," in part:
            pieces = part.split(",", 1)
            last = pieces[0].strip()
            first = pieces[1].strip()
        else:
            # Single name or unusual format
            words = part.split()
            if len(words) >= 2:
                last = words[-1]
                first = " ".join(words[:-1])
            else:
                last = part
                first = ""
        authors.append((last, first))
    return authors


def _get_last_name(author_tuple: tuple[str, str]) -> str:
    """Extract a clean last name for sorting/display."""
    last = author_tuple[0]
    # Clean LaTeX markup like {\"u} -> u (for display)
    last = re.sub(r'\{"?\\"\w*\}', "", last)
    # Remove remaining braces
    last = last.replace("{", "").replace("}", "")
    return last


def _initial(first_name: str) -> str:
    """Get the first initial from a first name, with period."""
    first_name = first_name.strip()
    if not first_name:
        return ""
    # Handle LaTeX-encoded names
    clean = re.sub(r"\{[^}]*\}", "", first_name).strip()
    if clean:
        return clean[0] + "."
    return first_name[0] + "."


def _format_authors_apa(author_str: str) -> str:
    """APA 7th: Last, F., Last, F., & Last, F."""
    authors = _parse_author_parts(author_str)
    formatted = []
    for last, first in authors:
        clean_last = _get_last_name((last, first))
        # Keep the original last name for display (with special chars)
        display_last = last.replace("{", "").replace("}", "").replace('"', "").replace("\\", "")
        ini = _initial(first)
        formatted.append(f"{display_last}, {ini}" if ini else display_last)

    if len(formatted) == 1:
        return formatted[0]
    elif len(formatted) == 2:
        return f"{formatted[0]}, & {formatted[1]}"
    else:
        return ", ".join(formatted[:-1]) + ", & " + formatted[-1]


def _format_authors_nature(author_str: str) -> str:
    """Nature: Last, F., Last, F."""
    authors = _parse_author_parts(author_str)
    formatted = []
    for last, first in authors:
        display_last = last.replace("{", "").replace("}", "").replace('"', "").replace("\\", "")
        ini = _initial(first)
        formatted.append(f"{display_last}, {ini}" if ini else display_last)
    return ", ".join(formatted)


def _format_authors_ieee(author_str: str) -> str:
    """IEEE: F. Last and F. Last."""
    authors = _parse_author_parts(author_str)
    formatted = []
    for last, first in authors:
        display_last = last.replace("{", "").replace("}", "").replace('"', "").replace("\\", "")
        ini = _initial(first)
        formatted.append(f"{ini} {display_last}" if ini else display_last)

    if len(formatted) <= 2:
        return " and ".join(formatted)
    else:
        return ", ".join(formatted[:-1]) + ", and " + formatted[-1]


def _format_authors_vancouver(author_str: str) -> str:
    """Vancouver: Last F, Last F (no periods after initials)."""
    authors = _parse_author_parts(author_str)
    formatted = []
    for last, first in authors:
        display_last = last.replace("{", "").replace("}", "").replace('"', "").replace("\\", "")
        ini = _initial(first).replace(".", "")  # No period
        formatted.append(f"{display_last} {ini}" if ini else display_last)
    return ", ".join(formatted)


# ---------------------------------------------------------------------------
# Citation Formatting
# ---------------------------------------------------------------------------


def format_citation(entry: dict, style: str) -> str:
    """Format a single bibliography entry in the given citation style.

    Args:
        entry: Dict from parse_bib_file with entry_type, key, title, author, etc.
        style: One of 'apa', 'nature', 'ieee', 'vancouver'.

    Returns:
        Formatted citation string.
    """
    style = style.lower()
    if style not in SUPPORTED_STYLES:
        raise ValueError(f"Unsupported style: {style}. Use one of {SUPPORTED_STYLES}")

    title = entry.get("title", "Untitled")
    year = entry.get("year", "n.d.")
    author_str = entry.get("author", "Unknown")
    journal = entry.get("journal", "")
    booktitle = entry.get("booktitle", "")
    doi = entry.get("doi", "")
    eprint = entry.get("eprint", "")
    venue = journal or booktitle

    if style == "apa":
        return _format_citation_apa(author_str, year, title, venue, doi, eprint)
    elif style == "nature":
        return _format_citation_nature(author_str, year, title, venue, doi, eprint)
    elif style == "ieee":
        return _format_citation_ieee(author_str, year, title, venue, doi, eprint)
    elif style == "vancouver":
        return _format_citation_vancouver(author_str, year, title, venue, doi, eprint)
    return ""


def _format_citation_apa(
    author_str: str, year: str, title: str, venue: str, doi: str, eprint: str
) -> str:
    """APA 7th: Authors (Year). Title. *Journal*. DOI"""
    authors = _format_authors_apa(author_str)
    parts = [f"{authors} ({year}). {title}."]
    if venue:
        parts.append(f"*{venue}*.")
    if doi:
        parts.append(f"https://doi.org/{doi}")
    elif eprint:
        parts.append(f"arXiv:{eprint}")
    return " ".join(parts)


def _format_citation_nature(
    author_str: str, year: str, title: str, venue: str, doi: str, eprint: str
) -> str:
    """Nature: Authors. Title. *Journal* (Year). DOI"""
    authors = _format_authors_nature(author_str)
    parts = [f"{authors}."]
    parts.append(f"{title}.")
    if venue:
        parts.append(f"*{venue}* ({year}).")
    else:
        parts.append(f"({year}).")
    if doi:
        parts.append(f"https://doi.org/{doi}")
    elif eprint:
        parts.append(f"arXiv:{eprint}")
    return " ".join(parts)


def _format_citation_ieee(
    author_str: str, year: str, title: str, venue: str, doi: str, eprint: str
) -> str:
    """IEEE: Authors, "Title," *Journal*, Year, doi: DOI."""
    authors = _format_authors_ieee(author_str)
    parts = [f'{authors}, "{title},"']
    if venue:
        parts.append(f"*{venue}*,")
    parts.append(f"{year},")
    if doi:
        parts.append(f"doi: {doi}.")
    elif eprint:
        parts.append(f"arXiv: {eprint}.")
    else:
        # Remove trailing comma from year and add period
        parts[-1] = parts[-1].rstrip(",") + "."
    return " ".join(parts)


def _format_citation_vancouver(
    author_str: str, year: str, title: str, venue: str, doi: str, eprint: str
) -> str:
    """Vancouver: Authors. Title. Journal. Year. doi: DOI"""
    authors = _format_authors_vancouver(author_str)
    parts = [f"{authors}. {title}."]
    if venue:
        parts.append(f"{venue}.")
    parts.append(f"{year}.")
    if doi:
        parts.append(f"doi: {doi}")
    elif eprint:
        parts.append(f"arXiv: {eprint}")
    return " ".join(parts)


# ---------------------------------------------------------------------------
# In-text Citation Formatting
# ---------------------------------------------------------------------------


def format_intext(entry: dict, style: str, number: int = 1) -> str:
    """Generate an in-text citation string.

    Args:
        entry: Dict from parse_bib_file.
        style: One of 'apa', 'nature', 'ieee', 'vancouver'.
        number: Citation number for numbered styles (nature, ieee, vancouver).

    Returns:
        Formatted in-text citation string.
    """
    style = style.lower()
    author_str = entry.get("author", "Unknown")
    year = entry.get("year", "n.d.")

    if style == "apa":
        authors = _parse_author_parts(author_str)
        if len(authors) == 1:
            last = _get_last_name(authors[0])
            return f"({last}, {year})"
        elif len(authors) == 2:
            last1 = _get_last_name(authors[0])
            last2 = _get_last_name(authors[1])
            return f"({last1} & {last2}, {year})"
        else:
            last = _get_last_name(authors[0])
            return f"({last} et al., {year})"
    elif style == "nature":
        return f"[{number}]"
    elif style == "ieee":
        return f"[{number}]"
    elif style == "vancouver":
        return f"({number})"
    else:
        raise ValueError(f"Unsupported style: {style}")


# ---------------------------------------------------------------------------
# Bibliography Generation
# ---------------------------------------------------------------------------


def format_bibliography(entries: list[dict], style: str) -> str:
    """Generate a full references section from a list of entries.

    Entries are sorted alphabetically by first author last name.
    Numbered styles (nature, ieee, vancouver) prepend [N] to each entry.

    Args:
        entries: List of entry dicts from parse_bib_file.
        style: One of 'apa', 'nature', 'ieee', 'vancouver'.

    Returns:
        Formatted bibliography as a markdown string with ## References header.
    """
    # Sort alphabetically by first author last name
    def sort_key(entry: dict) -> str:
        author_str = entry.get("author", "ZZZ")
        parts = _parse_author_parts(author_str)
        if parts:
            return _get_last_name(parts[0]).lower()
        return "zzz"

    sorted_entries = sorted(entries, key=sort_key)

    lines = ["## References", ""]
    numbered = style.lower() in ("nature", "ieee", "vancouver")

    for i, entry in enumerate(sorted_entries, 1):
        citation = format_citation(entry, style)
        if numbered:
            lines.append(f"[{i}] {citation}")
        else:
            lines.append(citation)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tier F — Per-claim deep links
# ---------------------------------------------------------------------------

_TEXT_FRAGMENT_MAX_CHARS = 100


def resolve_deep_link_url(
    entry: dict,
    quote: str = "",
    source_anchor: str = "",
) -> str:
    """Return a URL that lands the reader on the specific passage.

    Priority:
      1. paperclip anchor  (citations.gxl.ai/...#L<n>) — already exact
      2. DOI + #:~:text=<snippet>  (Chromium text fragment)
      3. arXiv + #:~:text=<snippet>
      4. plain DOI / arXiv URL (no fragment) — last resort

    Text fragment spec: https://wicg.github.io/scroll-to-text-fragment/
    Not all browsers support it, but it degrades to the base URL gracefully.
    PDF links won't honour it — documented limitation (see PLAN-V2 Tier-F risk 3).
    """
    if source_anchor and "citations.gxl.ai" in source_anchor:
        return source_anchor

    snippet = ""
    if quote:
        # Take the first ~100 chars, stop at a word boundary
        raw = quote.strip()[:_TEXT_FRAGMENT_MAX_CHARS]
        last_space = raw.rfind(" ")
        if last_space > 20:
            raw = raw[:last_space]
        snippet = urllib.parse.quote(raw, safe="")

    doi = (entry.get("doi") or "").strip()
    eprint = (entry.get("eprint") or "").strip()

    if doi:
        base = f"https://doi.org/{doi}"
        return f"{base}#:~:text={snippet}" if snippet else base
    if eprint:
        base = f"https://arxiv.org/abs/{eprint}"
        return f"{base}#:~:text={snippet}" if snippet else base

    url = (entry.get("url") or "").strip()
    return url


def format_bibliography_with_deep_links(
    entries: list[dict],
    style: str,
    sidecar: dict | None = None,
) -> str:
    """Generate a references section where each entry URL is a deep link.

    Each entry gets a markdown hyperlink using resolve_deep_link_url so the
    reader clicks directly to the cited passage rather than the paper root.

    Args:
        entries: List of entry dicts from parse_bib_file.
        style: One of 'apa', 'nature', 'ieee', 'vancouver'.
        sidecar: Optional parsed citations sidecar dict (from
            load_citations_sidecar). When present, the sidecar quote and
            source_anchor for each key inform the fragment URL.

    Returns:
        Formatted bibliography as a markdown string with ## References header.
    """
    claims_by_key: dict[str, dict] = {}
    if sidecar:
        for claim in sidecar.get("claims", []):
            k = (claim.get("key") or "").strip().lower()
            if k:
                claims_by_key[k] = claim

    def sort_key(e: dict) -> str:
        parts = _parse_author_parts(e.get("author", "ZZZ"))
        return _get_last_name(parts[0]).lower() if parts else "zzz"

    sorted_entries = sorted(entries, key=sort_key)
    numbered = style.lower() in ("nature", "ieee", "vancouver")

    lines = ["## References", ""]
    for i, entry in enumerate(sorted_entries, 1):
        key = (entry.get("key") or "").lower()
        claim = claims_by_key.get(key, {})
        quote = (claim.get("quote") or "").strip()
        source_anchor = (claim.get("source_anchor") or "").strip()

        citation_text = format_citation(entry, style)
        deep_url = resolve_deep_link_url(entry, quote=quote, source_anchor=source_anchor)

        if deep_url:
            # Wrap the URL portion as a markdown link: [citation text](url)
            entry_str = f"[{citation_text}]({deep_url})"
        else:
            entry_str = citation_text

        if numbered:
            lines.append(f"[{i}] {entry_str}")
        else:
            lines.append(entry_str)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Citation Marker Replacement
# ---------------------------------------------------------------------------


def replace_citation_markers(
    text: str, entries: list[dict], style: str
) -> tuple[str, list[str]]:
    """Replace [@key] citation markers in text with formatted citations.

    Handles single markers [@Key] and multi-cite markers [@Key1; @Key2].
    Key matching is case-insensitive. Unmatched keys generate warnings.

    Args:
        text: Draft text containing [@key] markers.
        entries: List of entry dicts from parse_bib_file.
        style: One of 'apa', 'nature', 'ieee', 'vancouver'.

    Returns:
        Tuple of (modified_text, list_of_warnings).
    """
    warnings: list[str] = []

    # Build case-insensitive key lookup and assign citation numbers
    # Sort entries alphabetically for consistent numbering
    def sort_key(entry: dict) -> str:
        author_str = entry.get("author", "ZZZ")
        parts = _parse_author_parts(author_str)
        if parts:
            return _get_last_name(parts[0]).lower()
        return "zzz"

    sorted_entries = sorted(entries, key=sort_key)
    key_map: dict[str, dict] = {}
    number_map: dict[str, int] = {}
    for i, entry in enumerate(sorted_entries, 1):
        key_lower = entry["key"].lower()
        key_map[key_lower] = entry
        number_map[key_lower] = i

    # Pattern: [@key] or [@key1; @key2; ...]
    marker_pattern = re.compile(r"\[@([^\]]+)\]")

    def replace_match(match: re.Match) -> str:
        inner = match.group(1)
        keys = [k.strip().lstrip("@") for k in inner.split(";")]

        resolved = []
        for key in keys:
            key_lower = key.lower()
            if key_lower in key_map:
                entry = key_map[key_lower]
                num = number_map[key_lower]
                resolved.append((entry, num))
            else:
                warnings.append(f"Unmatched citation key: {key}")

        if not resolved:
            return match.group(0)  # Leave unmatched markers as-is

        style_lower = style.lower()

        if style_lower == "apa":
            # APA multi-cite: "(Author1, Year1; Author2, Year2)"
            parts = []
            for entry, num in resolved:
                intext = format_intext(entry, "apa")
                # Strip outer parens for combining
                parts.append(intext[1:-1])
            return "(" + "; ".join(parts) + ")"

        elif style_lower == "nature":
            # Nature multi-cite: "[1,2]"
            nums = [str(num) for _, num in resolved]
            return "[" + ",".join(nums) + "]"

        elif style_lower == "ieee":
            # IEEE multi-cite: "[1], [2]"
            return ", ".join(f"[{num}]" for _, num in resolved)

        elif style_lower == "vancouver":
            # Vancouver multi-cite: "(1,2)"
            nums = [str(num) for _, num in resolved]
            return "(" + ",".join(nums) + ")"

        return match.group(0)

    result = marker_pattern.sub(replace_match, text)
    return result, warnings


# ---------------------------------------------------------------------------
# Reproducibility Logging
# ---------------------------------------------------------------------------


def log_citation_operation(
    operation: str,
    params: dict,
    bib_path: str = "",
    output_path: str = "",
) -> dict:
    """Log a citation formatting operation to the reproducibility ledger.

    Args:
        operation: Name of the operation (e.g., 'format_bibliography').
        params: Parameters used.
        bib_path: Path to .bib input file.
        output_path: Path to output file if any.

    Returns:
        The logged entry dict.
    """
    data_files = [bib_path] if bib_path and Path(bib_path).exists() else None
    output_files = [output_path] if output_path else None

    return log_operation(
        skill="sci-writing",
        operation=operation,
        params=params,
        data_files=data_files,
        output_files=output_files,
    )
